### ISSUE TITLE
Refactor Representatives legacy code

### ISSUE THREAD

**Issue by ashleygbui** [cs169/fa23-chips-10.5-14#9]
There is an unknown issue with the way the civic_api_to_representative_params method in the Representative model is implemented

1. Find the Error by exploring the codebase.  HINT: What happens if the method is called for a given representative who already exists in the database?
2. Write a characterization test to encapsulate your understanding, and modify the code to allow the test to pass
3. purge and re-initialize your database (why?), both locally and on Heroku.

**Comment by bentref** [comment]
Wrong repository...
